"""Ideals, which are to rings what normal subgroups are to groups.

An ideal is an additive subgroup that absorbs multiplication by the whole
ring, and that absorption is exactly what makes the quotient a ring. In the
residues modulo n every ideal is generated by a single element, and there are
as many of them as n has divisors, which the tests check for n = 12.
"""

import itertools
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "rings"))
import rings


def is_ideal(ring, subset):
    """Whether the subset is an additive subgroup absorbing the ring."""
    members = set(subset)
    if ring.zero() not in members:
        return False
    for left in members:
        if ring.negative(left) not in members:
            return False
        for right in members:
            if ring.add(left, right) not in members:
                return False
        for element in ring.elements:
            if ring.multiply(element, left) not in members:
                return False
            if ring.multiply(left, element) not in members:
                return False
    return True


def generated(ring, element):
    """The smallest ideal containing the element."""
    found = {ring.zero()}
    while True:
        additions = set()
        for member in found:
            for other in ring.elements:
                additions.add(ring.multiply(member, other))
                additions.add(ring.add(member, element))
                additions.add(ring.add(member, other and ring.multiply(element,
                                                                       other)))
        additions.add(element)
        additions = {item for item in additions if item not in found}
        if not additions:
            return frozenset(found)
        found |= additions


def all_ideals(ring):
    """Every ideal of the ring, found by testing every subset that could be one."""
    found = []
    seen = set()
    for element in ring.elements:
        ideal = generated(ring, element)
        if ideal not in seen:
            seen.add(ideal)
            found.append(ideal)
    return found


def is_principal(ring, ideal):
    """Whether some single element generates the ideal."""
    return any(generated(ring, element) == frozenset(ideal)
               for element in ideal)


def sum_of(ring, first, second):
    """The ideal of all sums of a member of each."""
    return frozenset(ring.add(left, right) for left in first for right in second)


def quotient(ring, ideal):
    """The ring of cosets of the ideal."""
    if not is_ideal(ring, ideal):
        raise ValueError("this subset is not an ideal")
    representatives = []
    lookup = {}
    for element in ring.elements:
        coset = frozenset(ring.add(element, member) for member in ideal)
        key = frozenset(map(str, coset))
        if key not in lookup:
            lookup[key] = element
            representatives.append(element)
    index = {}
    for element in ring.elements:
        coset = frozenset(map(str, (ring.add(element, member) for member in ideal)))
        index[element] = lookup[coset]

    return rings.Ring(representatives,
                      lambda a, b: index[ring.add(a, b)],
                      lambda a, b: index[ring.multiply(a, b)],
                      "%s/I" % (ring.name or "R"))
